"""
Mock Customer Data

10 realistic Indian customer profiles for testing.
"""

MOCK_CUSTOMERS = [
    {
        "id": "c1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6",
        "name": "Rajesh Kumar Sharma",
        "phone": "9876543210",
        "email": "rajesh.sharma@email.com",
        "pan": "ABCPS1234K",
        "aadhar_last_four": "5678",
        "address": "A-123, Vasant Kunj",
        "city": "New Delhi",
        "state": "Delhi",
        "pincode": "110070",
        "date_of_birth": "1985-06-15",
        "monthly_salary": 85000,
        "employer_name": "TCS",
        "employment_type": "SALARIED",
        "employment_years": 8,
        "credit_score": 782,
        "pre_approved_limit": 500000,
        "kyc_verified": True
    },
    {
        "id": "c2b3c4d5-e6f7-a8b9-c0d1-e2f3a4b5c6d7",
        "name": "Priya Patel",
        "phone": "9898765432",
        "email": "priya.patel@gmail.com",
        "pan": "BQLPP5678M",
        "aadhar_last_four": "1234",
        "address": "B-456, Satellite",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pincode": "380015",
        "date_of_birth": "1990-03-22",
        "monthly_salary": 120000,
        "employer_name": "Infosys",
        "employment_type": "SALARIED",
        "employment_years": 6,
        "credit_score": 810,
        "pre_approved_limit": 800000,
        "kyc_verified": True
    },
    {
        "id": "c3c4d5e6-f7a8-b9c0-d1e2-f3a4b5c6d7e8",
        "name": "Amit Singh",
        "phone": "9123456789",
        "email": "amit.singh@outlook.com",
        "pan": "CQXPS9012L",
        "aadhar_last_four": "9012",
        "address": "C-789, Koramangala",
        "city": "Bangalore",
        "state": "Karnataka",
        "pincode": "560034",
        "date_of_birth": "1988-11-08",
        "monthly_salary": 150000,
        "employer_name": "Google India",
        "employment_type": "SALARIED",
        "employment_years": 10,
        "credit_score": 845,
        "pre_approved_limit": 1500000,
        "kyc_verified": True
    },
    {
        "id": "c4d5e6f7-a8b9-c0d1-e2f3-a4b5c6d7e8f9",
        "name": "Sneha Reddy",
        "phone": "9988776655",
        "email": "sneha.reddy@yahoo.com",
        "pan": "DTYPR3456N",
        "aadhar_last_four": "3456",
        "address": "D-101, Banjara Hills",
        "city": "Hyderabad",
        "state": "Telangana",
        "pincode": "500034",
        "date_of_birth": "1992-07-30",
        "monthly_salary": 95000,
        "employer_name": "Amazon",
        "employment_type": "SALARIED",
        "employment_years": 5,
        "credit_score": 765,
        "pre_approved_limit": 600000,
        "kyc_verified": True
    },
    {
        "id": "c5e6f7a8-b9c0-d1e2-f3a4-b5c6d7e8f9a0",
        "name": "Vikram Mehta",
        "phone": "8765432109",
        "email": "vikram.mehta@business.com",
        "pan": "EABPM7890J",
        "aadhar_last_four": "7890",
        "address": "E-202, Andheri West",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pincode": "400058",
        "date_of_birth": "1982-01-14",
        "monthly_salary": 200000,
        "employer_name": "Self Employed",
        "employment_type": "SELF_EMPLOYED",
        "employment_years": 12,
        "credit_score": 720,
        "pre_approved_limit": 1000000,
        "kyc_verified": True
    },
    {
        "id": "c6f7a8b9-c0d1-e2f3-a4b5-c6d7e8f9a0b1",
        "name": "Ananya Gupta",
        "phone": "7654321098",
        "email": "ananya.gupta@company.com",
        "pan": "FCQPG2345H",
        "aadhar_last_four": "2345",
        "address": "F-303, Salt Lake",
        "city": "Kolkata",
        "state": "West Bengal",
        "pincode": "700091",
        "date_of_birth": "1995-09-05",
        "monthly_salary": 65000,
        "employer_name": "Wipro",
        "employment_type": "SALARIED",
        "employment_years": 3,
        "credit_score": 690,
        "pre_approved_limit": 300000,
        "kyc_verified": True
    },
    {
        "id": "c7a8b9c0-d1e2-f3a4-b5c6-d7e8f9a0b1c2",
        "name": "Suresh Iyer",
        "phone": "6543210987",
        "email": "suresh.iyer@tech.com",
        "pan": "GABPI6789G",
        "aadhar_last_four": "6789",
        "address": "G-404, T Nagar",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600017",
        "date_of_birth": "1987-04-20",
        "monthly_salary": 110000,
        "employer_name": "HCL",
        "employment_type": "SALARIED",
        "employment_years": 9,
        "credit_score": 795,
        "pre_approved_limit": 700000,
        "kyc_verified": True
    },
    {
        "id": "c8b9c0d1-e2f3-a4b5-c6d7-e8f9a0b1c2d3",
        "name": "Deepika Nair",
        "phone": "9012345678",
        "email": "deepika.nair@mail.com",
        "pan": "HCDPN0123F",
        "aadhar_last_four": "0123",
        "address": "H-505, MG Road",
        "city": "Kochi",
        "state": "Kerala",
        "pincode": "682016",
        "date_of_birth": "1991-12-12",
        "monthly_salary": 75000,
        "employer_name": "Infosys",
        "employment_type": "SALARIED",
        "employment_years": 4,
        "credit_score": 740,
        "pre_approved_limit": 450000,
        "kyc_verified": True
    },
    {
        "id": "c9c0d1e2-f3a4-b5c6-d7e8-f9a0b1c2d3e4",
        "name": "Rohit Malhotra",
        "phone": "8901234567",
        "email": "rohit.malhotra@startup.io",
        "pan": "IEFPM4567E",
        "aadhar_last_four": "4567",
        "address": "I-606, Sector 62",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "pincode": "201301",
        "date_of_birth": "1993-08-28",
        "monthly_salary": 180000,
        "employer_name": "Startup Inc",
        "employment_type": "SALARIED",
        "employment_years": 2,
        "credit_score": 680,
        "pre_approved_limit": 400000,
        "kyc_verified": False
    },
    {
        "id": "c0d1e2f3-a4b5-c6d7-e8f9-a0b1c2d3e4f5",
        "name": "Kavita Desai",
        "phone": "7890123456",
        "email": "kavita.desai@corp.org",
        "pan": "JGHPD8901D",
        "aadhar_last_four": "8901",
        "address": "J-707, FC Road",
        "city": "Pune",
        "state": "Maharashtra",
        "pincode": "411004",
        "date_of_birth": "1989-02-17",
        "monthly_salary": 130000,
        "employer_name": "Persistent Systems",
        "employment_type": "SALARIED",
        "employment_years": 7,
        "credit_score": 820,
        "pre_approved_limit": 900000,
        "kyc_verified": True
    }
]


# Mock credit bureau data
MOCK_CREDIT_SCORES = {
    "ABCPS1234K": {
        "credit_score": 782,
        "active_accounts": 4,
        "total_outstanding": 250000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.35,
        "payment_history_score": 95
    },
    "BQLPP5678M": {
        "credit_score": 810,
        "active_accounts": 3,
        "total_outstanding": 180000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.25,
        "payment_history_score": 98
    },
    "CQXPS9012L": {
        "credit_score": 845,
        "active_accounts": 5,
        "total_outstanding": 500000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.20,
        "payment_history_score": 100
    },
    "DTYPR3456N": {
        "credit_score": 765,
        "active_accounts": 3,
        "total_outstanding": 120000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.30,
        "payment_history_score": 92
    },
    "EABPM7890J": {
        "credit_score": 720,
        "active_accounts": 6,
        "total_outstanding": 800000,
        "delinquent_accounts": 1,
        "credit_utilization": 0.45,
        "payment_history_score": 85
    },
    "FCQPG2345H": {
        "credit_score": 690,
        "active_accounts": 2,
        "total_outstanding": 50000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.40,
        "payment_history_score": 80
    },
    "GABPI6789G": {
        "credit_score": 795,
        "active_accounts": 4,
        "total_outstanding": 300000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.28,
        "payment_history_score": 96
    },
    "HCDPN0123F": {
        "credit_score": 740,
        "active_accounts": 2,
        "total_outstanding": 100000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.32,
        "payment_history_score": 88
    },
    "IEFPM4567E": {
        "credit_score": 680,
        "active_accounts": 3,
        "total_outstanding": 400000,
        "delinquent_accounts": 1,
        "credit_utilization": 0.55,
        "payment_history_score": 75
    },
    "JGHPD8901D": {
        "credit_score": 820,
        "active_accounts": 4,
        "total_outstanding": 220000,
        "delinquent_accounts": 0,
        "credit_utilization": 0.22,
        "payment_history_score": 97
    }
}
